name: Quick Build

on: [push, pull_request]

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v4
        with:
        # Semantic version range syntax or exact version of a dotnet version
            dotnet-version: '8.x'
            #cache: true
      - name: Install dependencies
        run: dotnet restore mobileuo.sln
      - name: Build
        run: dotnet build mobileuo.sln --no-restore